CREATE TABLE IF NOT EXISTS event
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    max_places INTEGER NOT NULL CHECK (max_places >= 0),
    date TEXT NOT NULL,
    cost INTEGER NOT NULL CHECK (cost >= 1),
    duration INTEGER NOT NULL CHECK (duration >= 30),
    location_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    occupied_places INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'WAIT_START',
    CONSTRAINT fk_event_location FOREIGN KEY (location_id) REFERENCES location(id) ON DELETE NO ACTION,
    CONSTRAINT fk_event_owner FOREIGN KEY (owner_id) REFERENCES "user"(id) ON DELETE NO ACTION
);